In [2]:
import numpy as np 

lista = [1, 2, 3, 4 , 5 ,6]

array = np.array(lista)

print(type(lista))
print(type(array))


<class 'list'>
<class 'numpy.ndarray'>


In [3]:
arr_zeros= np.zeros(10)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
array[0]=9
print(array[0])

9


In [5]:
array[0]=9
print(array)

[9 2 3 4 5 6]


In [6]:
##matrizes 
matriz_zeros= np.zeros((5,3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
##notas de alunos

lista_de_notas=[9.5,8.0,5.4,3.6,7,5]

notas= np.array(lista_de_notas)

print('Máximo', notas.max())
print('Mínimo',notas.min())
print('Desvio Padrao', notas.std())
print ('Média', notas.mean())
print('Posição do menor', notas.argmin())
print('Posição do maior', notas.argmax())

Máximo 9.5
Mínimo 3.6
Desvio Padrao 1.9718152944826135
Média 6.416666666666667
Posição do menor 3
Posição do maior 0
